[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"

remappings = [
    "openzeppelin/=lib/openzeppelin-contracts/",
    "openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable/",
]

[rpc_endpoints]
mainnet = "${ETH_RPC_URL}"


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
